name: GithubActions Demo
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up
        uses: fwilhe2/setup-kotlin@main
      - name: Compile
        run: kotlinc main.kt -include-runtime -d /tmp/hello.jar
      - name: Run test
        run: java -jar /tmp/hello.jar   
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: Build Artifact
          path: /tmp/hello.jar
          # The desired behavior if no files are found using the provided path.
    
