name: Tags
on:
  push:
    tags:
      -'*'
    tags-ignore:
      - '2.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up
        uses: fwilhe2/setup-kotlin@main
      - name: Compile
        run: kotlinc main.kt -include-runtime -d /tmp/hello.jar
      - name: Run test
        run: java -jar /tmp/hello.jar   
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: Build Artifact
          path: /tmp/hello.jar
          # The desired behavior if no files are found using the provided path.
      - name: Upload Release Asset
        # You may pin to the exact commit or the version.
        # uses: tanyagray/action-upload-release-asset@6f7cb885466e94be7b52b5b7f8d7974178d5c15d
        uses: tanyagray/action-upload-release-asset@v1.1.3
        with:
          # The URL for uploading assets to the release
          upload_url: 
          # The path to the asset you want to upload
          asset_path: 
          # The name of the asset you want to upload
          asset_name: 
          # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
          asset_content_type: 
